import React from 'react';
import './About.css';

function About() {
  return (
    <div className="about">
      <div className="about-header">
        <h1>About This Research</h1>
        <p>Theoretical framework connecting quantum mechanics and genetic engineering</p>
      </div>

      <div className="container">
        <section className="about-section">
          <h2>Overview</h2>
          <p>
            This research proposes a theoretical framework for harnessing quantum entanglement at the cellular level 
            to overcome the delivery bottleneck in genetic medicine. Rather than physically transporting gene-editing tools 
            to every cell in the body, quantum entanglement enables instantaneous, organism-wide genetic correction through 
            a single targeted edit.
          </p>
          <p>
            While highly speculative, this framework is grounded in:
          </p>
          <ul>
            <li>Established quantum mechanics principles (entanglement, superposition, wave function collapse)</li>
            <li>Emerging quantum biology research (photosynthesis, bird migration, neural processes)</li>
            <li>Advanced gene-editing technologies (Prime Editing, CRISPR-Cas13)</li>
            <li>Cellular biology (Fröhlich mechanism, decoherence shields, protein qubits)</li>
          </ul>
        </section>

        <section className="about-section">
          <h2>Key Concepts</h2>
          
          <div className="concept-grid">
            <div className="concept-card">
              <h3>⚛️ Quantum Entanglement</h3>
              <p>
                When particles are entangled, the state of one particle instantaneously determines the state of another, 
                regardless of distance. A quantum measurement on one particle forces all entangled partners into a correlated state.
              </p>
            </div>

            <div className="concept-card">
              <h3>🧬 Cellular Qubits (EYFP)</h3>
              <p>
                Enhanced Yellow Fluorescent Proteins can function as spin qubits within living cells. Recent research (Feder et al., 2025) 
                shows EYFP proteins maintain quantum coherence even in the noisy cellular environment.
              </p>
            </div>

            <div className="concept-card">
              <h3>🔄 Fröhlich Mechanism</h3>
              <p>
                Biological systems can harness ambient thermal energy to create and sustain macroscopic quantum coherence. 
                Microtubules vibrate in synchronized patterns, creating "Fröhlich Bose-Einstein condensates" that protect quantum states.
              </p>
            </div>

            <div className="concept-card">
              <h3>💧 Decoherence Shields</h3>
              <p>
                Ordered water lattices, enzyme pockets, and myelin sheaths act as "decoherence-free" spaces where quantum states 
                can persist despite the warm, wet, noisy cellular environment.
              </p>
            </div>

            <div className="concept-card">
              <h3>🌊 Biophoton Networks</h3>
              <p>
                Entangled photon pairs (biophotons) are generated by cellular processes and can travel through tissues, 
                linking distant cellular components and enabling quantum information transfer.
              </p>
            </div>

            <div className="concept-card">
              <h3>📏 Quantum Measurement</h3>
              <p>
                When a gene-editing enzyme reads and modifies DNA at the quantum level, it acts as a measurement that collapses 
                the wave function, forcing all entangled cells into the same genetic state.
              </p>
            </div>
          </div>
        </section>

        <section className="about-section">
          <h2>The Three Experiments</h2>

          <div className="experiments-list">
            <div className="experiment-card">
              <h3>1. Cellular Entanglement Procedure</h3>
              <p>
                <strong>Goal:</strong> Establish quantum entanglement across all cells in an organism
              </p>
              <p>
                <strong>Method:</strong> EYFP-fusion gene editors are excited via near-infrared optical and microwave pulses, 
                forcing them into a synchronized quantum entangled state sustained by the Fröhlich mechanism.
              </p>
              <p>
                <strong>Stages:</strong>
              </p>
              <ol>
                <li>Initial state - independent EYFP-fusion proteins in each cell</li>
                <li>Fröhlich coherence activation - microtubules synchronized via thermal energy pumping</li>
                <li>Near-IR pulse initiation - EYFP qubits excited simultaneously</li>
                <li>Quantum entanglement collapse - all qubits adopt correlated state</li>
                <li>Organism-wide quantum network established</li>
              </ol>
            </div>

            <div className="experiment-card">
              <h3>2. Medical Experiment (In Vitro)</h3>
              <p>
                <strong>Disease Target:</strong> HBB mutation (sickle cell disease)
              </p>
              <p>
                <strong>Method:</strong> Entangled tissue culture has Prime Editor introduced to a single cell, correcting the HBB gene. 
                Quantum measurement forces all entangled cells to adopt the corrected state.
              </p>
              <p>
                <strong>Success Criterion:</strong> Unedited "bystander" cells spontaneously express corrected HBB sequence. 
                Daughter cells from mitosis inherit the edit.
              </p>
            </div>

            <div className="experiment-card">
              <h3>3. Biohacking Experiment (In Vitro & In Vivo)</h3>
              <p>
                <strong>Enhancement Target:</strong> Chloroplast integration into mammalian tissue (planimal cells)
              </p>
              <p>
                <strong>Method:</strong> Entangled tissue has Cas13 RNA editor targeting immune rejection genes in a single cell. 
                Quantum collapse propagates immune tolerance system-wide. Near-IR light stimulates photosynthesis.
              </p>
              <p>
                <strong>Success Criterion:</strong> Tissue produces oxygen internally and survives 15-minute hypoxia, proving 
                systemic edit successful.
              </p>
            </div>
          </div>
        </section>

        <section className="about-section">
          <h2>Major Challenges</h2>

          <div className="challenges-list">
            <div className="challenge-item">
              <h3>⚠️ Quantum Decoherence at Body Temperature</h3>
              <p>
                The cellular environment is "warm and noisy" - exactly hostile to quantum effects. Maintaining quantum coherence 
                at 37°C despite constant thermal disruption is the fundamental engineering challenge. Decoherence shields and the 
                Fröhlich mechanism are proposed solutions, but their sufficiency is unproven.
              </p>
            </div>

            <div className="challenge-item">
              <h3>⚠️ Scaling from Photons to Organisms</h3>
              <p>
                Quantum entanglement has been demonstrated with single photons and small qubit registers. Scaling to trillions of 
                cellular qubits while maintaining coherence represents an unprecedented engineering challenge with no clear solution.
              </p>
            </div>

            <div className="challenge-item">
              <h3>⚠️ Off-Target Edit Propagation</h3>
              <p>
                If the Prime Editor or Cas13 makes an off-target edit, quantum measurement could force ALL entangled cells to inherit 
                the error simultaneously. This creates systemic, organism-wide damage from a single mistake - a critical vulnerability.
              </p>
            </div>

            <div className="challenge-item">
              <h3>⚠️ Immunotoxicity of Editing Machinery</h3>
              <p>
                Constitutive expression of foreign gene-editing proteins (Prime Editor, Cas13) in all cells raises serious concerns 
                about immune activation, chronic inflammation, and long-term safety.
              </p>
            </div>

            <div className="challenge-item">
              <h3>⚠️ Regulatory Framework Gap</h3>
              <p>
                Systemic quantum entanglement editing poses ethical and regulatory challenges not addressed by current frameworks for 
                gene therapy. New regulatory paradigms must be developed.
              </p>
            </div>
          </div>
        </section>

        <section className="about-section">
          <h2>Why This Matters</h2>

          <p>
            If cellular entanglement biology were successfully developed, it would represent the most significant 
            advancement in medicine since antibiotics and vaccines. It would:
          </p>

          <ul>
            <li><strong>Eliminate the delivery bottleneck</strong> - the primary limitation of modern genetic medicine</li>
            <li><strong>Enable systemic disease treatment</strong> - late-stage cancers, systemic genetic disorders, and neurological diseases</li>
            <li><strong>Permit organism-wide enhancement</strong> - sensory expansion, metabolic redesign, longevity enhancement</li>
            <li><strong>Transform regenerative medicine</strong> - ethical stem cell sources and tissue engineering at scale</li>
            <li><strong>Reshape human biology</strong> - designer humans optimized for specific purposes or environments</li>
          </ul>

          <p style={{ marginTop: '2rem', fontSize: '1.1rem', fontStyle: 'italic' }}>
            The implications are profound. The science is speculative. The possibilities are transformative.
          </p>
        </section>

        <section className="about-section">
          <h2>About the Author</h2>

          <div className="author-box">
            <h3>Research Team</h3>
            <p>
              This theoretical framework was developed as an exploration of emerging concepts at the intersection of 
              quantum mechanics, molecular biology, and genetic engineering. It represents a synthesis of:
            </p>
            <ul>
              <li>Peer-reviewed quantum biology research</li>
              <li>Recent advances in gene-editing technologies</li>
              <li>Emerging understanding of cellular quantum processes</li>
              <li>Theoretical physics principles (entanglement, coherence, measurement)</li>
            </ul>
            <p style={{ marginTop: '1rem' }}>
              <strong>Disclaimer:</strong> This is a theoretical framework presented for educational and research purposes. 
              While grounded in established science, the specific proposals for cellular entanglement biology remain entirely speculative 
              and unproven. Significant technological breakthroughs would be required before any practical application.
            </p>
          </div>
        </section>

        <section className="about-section">
          <h2>References & Further Reading</h2>

          <h3>Key Papers Referenced</h3>
          <ul className="references-list">
            <li>Feder et al. (2025). Enhanced Yellow Fluorescent Protein Qubits in Living Cells</li>
            <li>Liu et al. (2024). Myelin Sheath Biphoton Cascade Emission and Neural Entanglement</li>
            <li>Shirmovsky & Chizhov (2025). Coherent Proton Qubits in DNA-Transcriptase Interactions</li>
            <li>Hubac et al. (2017). Hydrogen Bond Proton Dynamics and Genetic Information Processing</li>
            <li>Hameroff (2004). Quantum Processes in Biological Microtubules</li>
            <li>Abudayyeh et al. (2016). CRISPR-Cas13: RNA-Targeting Systems</li>
            <li>Hanna et al. (2020). Treatment Delay and Mortality Outcomes in Cancer</li>
            <li>Zhu et al. (2024). RNA Base Editors for Hearing Loss Prevention</li>
            <li>Newall (2025). Squirrel Monkey Vision Enhancement and Tetrachromacy</li>
            <li>Mubarik et al. (2025). Chloroplast Machinery Integration in Mammalian Cells</li>
          </ul>

          <h3>Recommended Further Reading</h3>
          <ul className="references-list">
            <li>Lambert et al. (2013). The Quantum World of Photosynthesis (Nature)</li>
            <li>Rydberg et al. (2015). Quantum Computing with Cold Atoms (Reviews of Modern Physics)</li>
            <li>Orzel (2017). Entanglement and Quantum Information</li>
            <li>Penrose & Hameroff (2014). Consciousness in the Universe (Updated Review)</li>
          </ul>
        </section>

        <section className="cta-section">
          <h2>Explore the Research</h2>
          <p>Delve deeper into the theoretical framework with the interactive simulation:</p>
          <a href="/demo" className="btn btn-primary">Launch Interactive Demo</a>
          <p style={{ marginTop: '1rem', fontSize: '0.9rem' }}>
            <a href="/theory" style={{ textDecoration: 'underline' }}>Read the full theoretical article →</a>
          </p>
        </section>
      </div>
    </div>
  );
}

export default About;
